#!/bin/bash
#
# omarchy-face v2
# omarchy-face-version: 2.0.4
#
# Every install of Face's system half -- the first one, an upgrade, and a
# repair -- and the only way root ever receives files from the plugin folder.
#
# The panel never runs this. The owner runs it from a terminal, with the command
# in the README ("Installing it"), which copies this file into a directory only
# root can write and checks it against the SHA-256 published in that README
# before running the copy:
#
#   bash <root-owned copy of this file> "$PLUGIN_DIR" "$USER"
#
# That published checksum is the trust anchor, and it is the one thing here that
# does not come from the plugin folder: the folder is writable by the account,
# and by any program running as it, so a script read out of it and run as root
# would be whatever that program last wrote. dev/update-pins.sh writes the
# checksum into the README, and dev/check-pins.sh refuses a stale one.
#
# The same goes for the files this installs. Nothing about a path is trusted. Root copies the ten system files
# into a directory only root could have created, checks every copied byte
# against a SHA-256 pinned below, in this authorised text, and from then on
# works only from that snapshot: the admin helper that does the install is run
# out of it, and installs out of it. A file swapped at any point before the
# copy fails its pin and nothing is installed.
#
# The pins below are generated by dev/update-pins.sh and checked by
# dev/check-pins.sh, which the repo's install.sh runs, so a stale pin cannot be
# synced or released.

set -uo pipefail
unset IFS BASH_ENV ENV CDPATH
# /usr/bin only. /usr/local/bin is where the helpers go, and this script checks
# that directory's ownership further down; every command before that check
# would otherwise already have resolved through it. Nothing here lives there.
PATH=/usr/bin
umask 022

CONFIG_FILE=/etc/omarchy-face/config

die() {
  printf '{"error":"%s"}\n' "$1"
  exit 1
}

[[ $EUID -eq 0 ]] || die "not_root"

PLUGIN_DIR=${1:-}
ACCOUNT=${2:-}

[[ -n $PLUGIN_DIR && -n $ACCOUNT ]] || die "bad_arguments"
[[ $PLUGIN_DIR == /* && $PLUGIN_DIR != *..* ]] || die "plugin_missing"
# A symlink would make the ownership check below a check on the link's target.
[[ ! -L $PLUGIN_DIR && ! -L $PLUGIN_DIR/system ]] || die "plugin_unsafe"
[[ -d $PLUGIN_DIR/system ]] || die "plugin_missing"
[[ $ACCOUNT != root ]] || die "unknown_account"
account_uid=$(id -u -- "$ACCOUNT" 2>/dev/null) || die "unknown_account"

# PKEXEC_UID is who INVOKED pkexec. It is not forgeable by the caller, and it is
# not a statement about who authenticated: the generic exec action is auth_admin,
# so an administrator approved this, but that administrator may be a different
# person from the account the plugin folder belongs to. Installing a third
# party's scripts as root is not what approving this dialog meant.
[[ -z ${PKEXEC_UID:-} || ${PKEXEC_UID:-} == "$account_uid" ]] || die "not_owner"
# The same rule for sudo, the way the README runs this: whoever typed the command
# is installing for their own account, not for somebody else's plugin folder.
[[ -z ${SUDO_UID:-} || ${SUDO_UID:-} == "$account_uid" ]] || die "not_owner"

# And the account being set up must itself be an administrator.
#
# Face's helpers run as root from sudo's PAM stack, and its own polkit action is
# auth_self: once installed, the owner changes what those helpers accept (who
# may use sudo by face) with THEIR OWN password. Setting Face up for an ordinary
# user would therefore hand that user a way to root that they did not have.
# Refusing here keeps the design honest: Face's owner is by construction an
# administrator, so nothing Face's own action allows grants more than the
# owner's password already does.
#
# The administrator identity is polkit's own, read from its default rules rather
# than assumed to be wheel.
admin_group=$(sed -n 's/.*unix-group:\([a-zA-Z0-9_.-]\+\).*/\1/p' \
  /usr/share/polkit-1/rules.d/50-default.rules 2>/dev/null | head -1)
: "${admin_group:=wheel}"
id -Gn -- "$ACCOUNT" 2>/dev/null | tr ' ' '\n' | grep -qxF "$admin_group" || die "not_admin"

# The plugin folder is the account's own or the system's. Anything else is a
# third party's directory (§5.1's trust boundary is "the owner's own files",
# not "any path handed to root").
owner_uid=$(stat -Lc %u "$PLUGIN_DIR/system" 2>/dev/null) || die "plugin_missing"
[[ $owner_uid == 0 || $owner_uid == "$account_uid" ]] || die "plugin_not_owned"

# An installed machine belongs to the account in its config. Installing for
# somebody else over it is Remove and then install, not an update.
#
# Parsed exactly as the admin helper's config_get parses it -- last assignment
# wins, comments and trailing space dropped -- so the two cannot come to
# different answers about who the machine belongs to.
if [[ -e $CONFIG_FILE ]]; then
  configured=$(sed -n "s/^[[:space:]]*account[[:space:]]*=[[:space:]]*//p" "$CONFIG_FILE" 2>/dev/null | tail -1)
  configured=${configured%%#*}
  configured=${configured%"${configured##*[![:space:]]}"}
  [[ $configured == "$ACCOUNT" ]] || die "not_owner"
fi

logger -t omarchy-face -p auth.notice -- \
  "install requested by uid ${PKEXEC_UID:-0} for $ACCOUNT from $PLUGIN_DIR" 2>/dev/null || true

# The release this text was generated for. Every file root installs must hash to
# exactly this; there is no other list, so a name missing here is never copied.
# pins:begin
declare -A PINS=(
  [omarchy-face-admin]=9409cc71d0e3f8a5fed106dc9912931ae3d46e7f35bb1ce75ecf504afdd13dd4
  [omarchy-face-gate]=0dc22474b2a9a5eaf58e6f86acb2aff9601e7d7f21c9ebf10aa5ce79c4dc6c49
  [omarchy-face-verify]=d61c77ba66fb6904ead96e96d7232d96609f62b385003760eee83b62dc30a367
  [omarchy-faced]=2cea3eddfc20fb5ce11728922b47bab0f8f4d9494c04a8eeb77fe2308a81a8f6
  [omarchy-face-identity]=c10dbfb4cee16c66f0c2edfb647d08660e8964f61e85bc3d4903d72b6d148cb6
  [omarchy-face-lock-verify]=2b6b34355e3b0fc47ba66aa1b486cd2423b46831d940caa4c4e83340f680f16c
  [omarchy-face-camera]=fe37e57e1c1c179254d20d26d90a1b4423337d9ee8a6ee2a98d9e4940350d65c
  [omarchy-faced.socket]=bef5ea6e4c7dd7c89c4df14c86617658c9892d29f29f559b9d9071397bdb0e4b
  [omarchy-faced.service]=77818242941a893b4bb7f5c071856fc30998c0304f918d7dea4fcf35513b3f94
  [no.graveklar.face.policy]=54ca9ab79473b68e8df25a7833c1d6b5a6526235dc329046331bf24c10338b58
)
# pins:end

# Snapshot, then check, then install from the snapshot. /run is root-owned, and
# mktemp -d makes the directory 0700 before anything is written into it.
tmp=$(mktemp -d /run/omarchy-face-install.XXXXXX) || die "snapshot_failed"
trap 'rm -rf -- "$tmp"' EXIT
chmod 0700 "$tmp" || die "snapshot_failed"

# Before copying, refuse what could never match a pin: anything but a plain
# file, and anything larger than a helper could be. This is only a cheap early
# refusal -- the source can still change after it -- so that root is not made to
# copy a directory tree or a multi-gigabyte file into /run. The checks on the
# snapshot below are the ones that decide.
MAX_BYTES=1048576
for name in "${!PINS[@]}"; do
  src=$PLUGIN_DIR/system/$name
  [[ -f $src && ! -L $src ]] || die "snapshot_unsafe"
  size=$(stat -c %s -- "$src" 2>/dev/null) || die "snapshot_incomplete"
  (( size <= MAX_BYTES )) || die "snapshot_unsafe"
done

# No -a: without -R a directory is refused rather than copied, and the copies
# are root's own files with root's umask rather than carrying the account's
# ownership and mode into the snapshot. --no-dereference still copies a link
# that appeared since the check above AS a link, for the check below to refuse.
for name in "${!PINS[@]}"; do
  cp --no-dereference --preserve=timestamps -- "$PLUGIN_DIR/system/$name" "$tmp/$name" 2>/dev/null ||
    die "snapshot_incomplete"
done

# Plain, single-link, bounded files only, checked one name at a time so that no
# failure of the check itself can read as a pass. A symlink would be followed by
# sha256sum and install; a second link would leave the inode reachable from
# outside the snapshot.
for name in "${!PINS[@]}"; do
  f=$tmp/$name
  [[ -f $f && ! -L $f ]] || die "snapshot_unsafe"
  shape=$(stat -c '%h %s %u' -- "$f" 2>/dev/null) || die "snapshot_unsafe"
  read -r links size uid <<<"$shape"
  [[ $links == 1 && $uid == 0 ]] || die "snapshot_unsafe"
  (( size <= MAX_BYTES )) || die "snapshot_unsafe"
done

# The bytes, not the path and not a header: a swapped file can carry any header
# it likes. From here on the snapshot is exactly the reviewed release.
for name in "${!PINS[@]}"; do
  got=$(sha256sum -- "$tmp/$name" 2>/dev/null) || die "snapshot_incomplete"
  [[ ${got%% *} == "${PINS[$name]}" ]] || die "snapshot_modified"
done

# The directory root helpers live in must be root's and writable by nobody else.
# A group-writable /usr/local/bin is a way to replace a file that PAM will run
# as root, and it costs one stat to refuse rather than to assume.
[[ -d /usr/local/bin ]] || install -d -o root -g root -m 0755 /usr/local/bin || die "install_failed"
dir_info=$(stat -Lc '%u %a' /usr/local/bin 2>/dev/null) || die "install_dir_unsafe"
[[ ${dir_info%% *} == 0 ]] || die "install_dir_unsafe"
dir_mode=${dir_info##* }
(( (8#$dir_mode & 8#022) == 0 )) || die "install_dir_unsafe"

# The verified admin helper does the install, run from the snapshot rather than
# installed first: its own version checks decide whether this release may
# replace what is there, and they must run before anything is replaced -- a
# refused downgrade has to leave the installed half exactly as it was.
#
# `env -u PKEXEC_UID`: --verified-snapshot is refused when PKEXEC_UID is set, so
# it cannot be reached through Face's own auth_self action. Here the caller is
# already root, and the account is passed explicitly.
#
# Not `exec`: exec replaces this process, the EXIT trap never runs, and the
# snapshot directory stays in /run until the next boot.
env -u PKEXEC_UID /bin/bash "$tmp/omarchy-face-admin" install-system --verified-snapshot "$tmp" "$ACCOUNT"
exit $?
