#!/bin/bash
#
# omarchy-face v2
# omarchy-face-version: 2.0.3
#
# Every install of Face's system half -- the first one, an upgrade, and a
# repair -- and the only way root ever receives files from the plugin folder.
#
#   pkexec /bin/bash -c "$INSTALL_SCRIPT" omarchy-face-install "$PLUGIN_DIR" "$USER"
#
# The GUI reads this file and passes its TEXT inline, so what polkit authorised
# is exactly the text that runs. The dialog the owner sees says "run /bin/bash
# as the super user" with no message of Face's own; Setup warns about that
# wording before the click.
#
# The plugin folder is writable by the account, and by any program running as
# it, right up to the moment root reads it -- including while that dialog is on
# screen. So nothing about a path is trusted. Root copies the ten system files
# into a directory only root could have created, checks every copied byte
# against a SHA-256 pinned below, in this authorised text, and from then on
# works only from that snapshot: the admin helper that does the install is run
# out of it, and installs out of it. A file swapped at any point before the
# copy fails its pin and nothing is installed.
#
# The pins are generated by dev/update-pins.sh and checked by dev/check-pins.sh,
# which the repo's install.sh runs, so a stale pin cannot be synced or released.

set -uo pipefail
unset IFS BASH_ENV ENV CDPATH
PATH=/usr/local/bin:/usr/bin
umask 022

CONFIG_FILE=/etc/omarchy-face/config

die() {
  printf '{"error":"%s"}\n' "$1"
  exit 1
}

[[ $EUID -eq 0 ]] || die "not_root"

PLUGIN_DIR=${1:-}
ACCOUNT=${2:-}

[[ -n $PLUGIN_DIR && -n $ACCOUNT ]] || die "bad_arguments"
[[ $PLUGIN_DIR == /* && $PLUGIN_DIR != *..* ]] || die "plugin_missing"
# A symlink would make the ownership check below a check on the link's target.
[[ ! -L $PLUGIN_DIR && ! -L $PLUGIN_DIR/system ]] || die "plugin_unsafe"
[[ -d $PLUGIN_DIR/system ]] || die "plugin_missing"
[[ $ACCOUNT != root ]] || die "unknown_account"
account_uid=$(id -u -- "$ACCOUNT" 2>/dev/null) || die "unknown_account"

# PKEXEC_UID is who INVOKED pkexec. It is not forgeable by the caller, and it is
# not a statement about who authenticated: the generic exec action is auth_admin,
# so an administrator approved this, but that administrator may be a different
# person from the account the plugin folder belongs to. Installing a third
# party's scripts as root is not what approving this dialog meant.
[[ -z ${PKEXEC_UID:-} || ${PKEXEC_UID:-} == "$account_uid" ]] || die "not_owner"

# And the account being set up must itself be an administrator.
#
# Face's helpers run as root from sudo's PAM stack, and its own polkit action is
# auth_self: once installed, the owner changes what those helpers accept (who
# may use sudo by face) with THEIR OWN password. Setting Face up for an ordinary
# user would therefore hand that user a way to root that they did not have.
# Refusing here keeps the design honest: Face's owner is by construction an
# administrator, so nothing Face's own action allows grants more than the
# owner's password already does.
#
# The administrator identity is polkit's own, read from its default rules rather
# than assumed to be wheel.
admin_group=$(sed -n 's/.*unix-group:\([a-zA-Z0-9_.-]\+\).*/\1/p' \
  /usr/share/polkit-1/rules.d/50-default.rules 2>/dev/null | head -1)
: "${admin_group:=wheel}"
id -Gn -- "$ACCOUNT" 2>/dev/null | tr ' ' '\n' | grep -qxF "$admin_group" || die "not_admin"

# The plugin folder is the account's own or the system's. Anything else is a
# third party's directory (§5.1's trust boundary is "the owner's own files",
# not "any path handed to root").
owner_uid=$(stat -Lc %u "$PLUGIN_DIR/system" 2>/dev/null) || die "plugin_missing"
[[ $owner_uid == 0 || $owner_uid == "$account_uid" ]] || die "plugin_not_owned"

# An installed machine belongs to the account in its config. Installing for
# somebody else over it is Remove and then install, not an update.
if [[ -e $CONFIG_FILE ]]; then
  configured=$(sed -n 's/^account=//p' "$CONFIG_FILE" 2>/dev/null | head -1)
  [[ $configured == "$ACCOUNT" ]] || die "not_owner"
fi

logger -t omarchy-face -p auth.notice -- \
  "install requested by uid ${PKEXEC_UID:-0} for $ACCOUNT from $PLUGIN_DIR" 2>/dev/null || true

# The release this text was generated for. Every file root installs must hash to
# exactly this; there is no other list, so a name missing here is never copied.
# pins:begin
declare -A PINS=(
  [omarchy-face-admin]=b2c27e531eb18773c66cc7bfecec6f5dd3425d7645f28fef9e14aaf500a5f762
  [omarchy-face-gate]=0edbaaab868eed4e6a0b6d7a2eacb592ea3bb5eae446b5005b53f3bf2a4097b7
  [omarchy-face-verify]=b6696d84d564c9259402e8f1d21c3fd2080df774a73a7a04a65241c77858282d
  [omarchy-faced]=eb1cd011199e4a1b1820e284f013f6c00cd17c93bc3ad485f450090e71b0ed75
  [omarchy-face-identity]=bc35682fc27b803105b8a89f2963b8b5cc9e11b641c1406b7175cc57890ae8d9
  [omarchy-face-lock-verify]=54fe58517f1570e8dc5d42dcf5ba71ad5c420318dc99d716b4229585b7334feb
  [omarchy-face-camera]=63d44830e3bcabdd2755176e39e0d9d0f1d643173d01d2fc6a573f5d18b89964
  [omarchy-faced.socket]=5d6b152436afc9167478e3634b786e0c8746d5bb6f988a1edfa7c1af04338b52
  [omarchy-faced.service]=d016bfd6916c4a72de681d2f7004df9da3c7fd12458d8bb7c0a8e8d58b97db01
  [no.graveklar.face.policy]=1af199c221e573e69508a6d940697398b530022f41846c84dc81768e7c234ddb
)
# pins:end

# Snapshot, then check, then install from the snapshot. /run is root-owned, and
# mktemp -d makes the directory 0700 before anything is written into it.
tmp=$(mktemp -d /run/omarchy-face-install.XXXXXX) || die "snapshot_failed"
trap 'rm -rf -- "$tmp"' EXIT
chmod 0700 "$tmp" || die "snapshot_failed"

for name in "${!PINS[@]}"; do
  cp -a --no-dereference "$PLUGIN_DIR/system/$name" "$tmp/$name" 2>/dev/null || die "snapshot_incomplete"
done

# Plain files only. A symlink would have been followed back out of the snapshot
# when it was installed, and a hard link leaves the same inode writable from
# outside it.
[[ -z $(find "$tmp" -mindepth 1 \( -type l -o -links +1 -o ! -type f \) -print -quit 2>/dev/null) ]] ||
  die "snapshot_unsafe"

# The bytes, not the path and not a header: a swapped file can carry any header
# it likes. From here on the snapshot is exactly the reviewed release.
for name in "${!PINS[@]}"; do
  got=$(sha256sum -- "$tmp/$name" 2>/dev/null) || die "snapshot_incomplete"
  [[ ${got%% *} == "${PINS[$name]}" ]] || die "snapshot_modified"
done

# The directory root helpers live in must be root's and writable by nobody else.
# A group-writable /usr/local/bin is a way to replace a file that PAM will run
# as root, and it costs one stat to refuse rather than to assume.
[[ -d /usr/local/bin ]] || install -d -o root -g root -m 0755 /usr/local/bin || die "install_failed"
dir_info=$(stat -Lc '%u %a' /usr/local/bin 2>/dev/null) || die "install_dir_unsafe"
[[ ${dir_info%% *} == 0 ]] || die "install_dir_unsafe"
dir_mode=${dir_info##* }
(( (8#$dir_mode & 8#022) == 0 )) || die "install_dir_unsafe"

# The verified admin helper does the install, run from the snapshot rather than
# installed first: its own version checks decide whether this release may
# replace what is there, and they must run before anything is replaced -- a
# refused downgrade has to leave the installed half exactly as it was.
#
# `env -u PKEXEC_UID`: --verified-snapshot is refused when PKEXEC_UID is set, so
# it cannot be reached through Face's own auth_self action. Here the caller is
# already root, and the account is passed explicitly.
#
# Not `exec`: exec replaces this process, the EXIT trap never runs, and the
# snapshot directory stays in /run until the next boot.
env -u PKEXEC_UID /bin/bash "$tmp/omarchy-face-admin" install-system --verified-snapshot "$tmp" "$ACCOUNT"
exit $?
